name: terraform

on:
  - pull_request

jobs:
  security:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1.1

  check_format:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: terraform

  run_plan:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-plan@v1
        with:
          path: terraform